language: python

python:
- 3.6
- 3.6-dev
- 3.7-dev
- 3.7

before_install:
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get -q update
  - sudo apt-get -y install git-annex-standalone

install:
- pip install -r requirements.txt
- pip install coveralls
- git config --global pull.rebase false

script:
- ./lint.sh
- pytest --cov ../conp-portal

after_success:
- coveralls
